### ISSUE TITLE
Insecure default permissions in backup script

### ISSUE THREAD

**Issue by maxbes** [ltb-project/openldap-initscript#21]
`slapd-cli backup` and `slapd-cli backupconfig` creates world-readable files in /var/backups/openldap/ by default.

```
[root@openldap-ltb-rpm ~]# ll /var/backups/openldap/openldap-data-20210301161856.ldif 
-rw-r--r-- 1 ldap ldap 0 Mar  1 16:18 /var/backups/openldap/openldap-data-20210301161856.ldif
```

This is a serious security issue. We should recommend affected users to restrict execute access to this directory, and set at least umask 0077 when doing the backup.

**Comment by davidcoutadeur** [comment]
My commit 65afe5c should fix the issue with a 0027 mask.
Two remarks:
- maybe could we also review owner of the files. Backups be considered as very confidential files, so maybe a set: root:ldap would be more appropriate?
- Future major OpenLDAP release seems to move forward very quickly, but we could still have an intermediate minor release... I think we should propose the fix for next release, whatever it is.

**Comment by coudot** [comment]
Thanks @davidcoutadeur for the fix

We could indeed maybe configure user/group used for backup files, it could be something else than the `ldap` user

Before releasing a new version of this script, we should maybe review 2.5 new features and see what could be useful here. Like the slapmodify tool for example.

**Comment by coudot** [comment]
@davidcoutadeur I would like to release 2.6 version of initscript to build 2.4.58 packages

@maxbes do you see other things to do before closing this issue?

**Comment by maxbes** [comment]
65afe5ccd7d03c985bcf3a36ade57bd68254631b fixes the issue, thanks
